global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'custom_metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Replace with your host IP if needed